/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qqclient;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

/**
 *
 * @author gillmylady
 */
public class QQClient extends javax.swing.JFrame {

    private static int port = 9002;
    private PrintWriter out;
    private String name = "initialname";
    
    /**
     * Creates new form QQClient
     */
    public QQClient() {
        initComponents();
        this.setVisible(true);
        this.jTextAreaLog.setEditable(false);
        this.jTextAreaFriends.setEditable(false);
        //this.jTextFieldEdit.setEditable(false);
        
        printPrompt("Client starts");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEdit = new javax.swing.JTextField();
        jComboBoxSelectFriend = new javax.swing.JComboBox<>();
        jScrollPaneFriends = new javax.swing.JScrollPane();
        jTextAreaFriends = new javax.swing.JTextArea();
        jScrollPaneLogArea = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditActionPerformed(evt);
            }
        });

        jComboBoxSelectFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectFriendActionPerformed(evt);
            }
        });

        jTextAreaFriends.setColumns(20);
        jTextAreaFriends.setRows(5);
        jScrollPaneFriends.setViewportView(jTextAreaFriends);

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPaneLogArea.setViewportView(jTextAreaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jComboBoxSelectFriend, 0, 91, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneLogArea, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jTextFieldEdit))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneLogArea, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSelectFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditActionPerformed
        // TODO add your handling code here:
         
         if(this.jTextFieldEdit.getText().startsWith("NAME:")){
             this.name = (this.jTextFieldEdit.getText().split(":"))[1];
         }
         
         // no msg is input
         if(this.jTextFieldEdit.getText().startsWith("CHAT") && this.jTextFieldEdit.getText().split(":").length > 3 && this.jTextFieldEdit.getText().split(":")[3].equals("")){
             return;
         }
             
         this.out.println(this.jTextFieldEdit.getText());
         
         // some msg is here, we only clear the msg
         if(this.jTextFieldEdit.getText().startsWith("CHAT") && this.jTextFieldEdit.getText().split(":").length > 3){
             String init = this.jTextFieldEdit.getText().split(":")[0] + ":" + this.jTextFieldEdit.getText().split(":")[1] + ":" + this.jTextFieldEdit.getText().split(":")[2] + ":";
             this.jTextFieldEdit.setText(init);
         }
         else{
            this.jTextFieldEdit.setText("");
         }
    }//GEN-LAST:event_jTextFieldEditActionPerformed

    private void jComboBoxSelectFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectFriendActionPerformed
        // TODO add your handling code here:
        this.jTextFieldEdit.setText("CHAT:" + this.name + ":"+ this.jComboBoxSelectFriend.getSelectedItem() + ":");
    }//GEN-LAST:event_jComboBoxSelectFriendActionPerformed

    
    private void printDebug(String s){
        //this.jTextAreaLog.append("\n##debug:" + s);
    }
    
    private void printPrompt(String s){
        this.jTextAreaLog.append("\n" + s);
    }
    
    private void getUserName(){
        printPrompt("Please input your name");
        //this.jTextFieldEdit.setEditable(true);
        this.jTextFieldEdit.setText("NAME:");
    }
    
    private void displayFriendList(String s){
        
        String friendList = "Friends:";
        for(String t : s.split(";")){
            friendList = friendList + "\n";
            friendList = friendList + t;
        }
        this.jTextAreaFriends.setText(friendList);
    }
    
    private void updateComboBoxList(String s){
        this.jComboBoxSelectFriend.removeAllItems();
        printDebug("combo box: " + s);
        String[] friendList = s.split(";");
        System.out.println(friendList.length);
        for(String t : friendList){
            printDebug("combo box: " + t);
            this.jComboBoxSelectFriend.addItem(t);
        }
    }
    
    public void runSocket() throws Exception{
        
        Socket socket = new Socket("localhost", port);
        BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        this.out = new PrintWriter(socket.getOutputStream(),true);
        System.out.println("start listening");
        while(true){
            printDebug("begin the while loop");
            String line = "";
            line = in.readLine();
            printDebug("read line: " + line);
            String[] info = line.split(":");
            String s1 = ""; String s2 = ""; String s3 = "";
            String s0 = "";
            
            if(info.length > 0)
                s0 = info[0];
            if(info.length > 1)
                s1 = info[1];
            if(info.length > 2)
                s2 = info[2];
            if(info.length > 3)
                s3 = info[3];

            if(s0.equals("NAME") && info.length == 1){
                printPrompt("Please input your name");
                this.jTextFieldEdit.setText("NAME:");
            }else if(s0.equals("CHAT") && s2.equals(this.name)){
                printPrompt(s1 + ": " + s3);       //display msg from others
            }else if(s0.equals("CHAT") && s1.equals(this.name)){
                printPrompt("To "+ s2 + ": " + s3);
            }else if(s0.equals("FRIENDS")){
                displayFriendList(s1);
                updateComboBoxList(s1);
            }else if(s0.equals("NAME") && info.length > 1){
                this.jTextFieldEdit.setText("");
            }
        }


                
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QQClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QQClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QQClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QQClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        QQClient client = new QQClient();
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                client.setVisible(true);
                
            }
        });
*/
        client.setVisible(true);
        client.runSocket();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSelectFriend;
    private javax.swing.JScrollPane jScrollPaneFriends;
    private javax.swing.JScrollPane jScrollPaneLogArea;
    private javax.swing.JTextArea jTextAreaFriends;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldEdit;
    // End of variables declaration//GEN-END:variables
}
